# Generated by Django 2.2.6 on 2020-03-21 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='d',
        ),
        migrations.RemoveField(
            model_name='question',
            name='r',
        ),
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op1', models.CharField(max_length=20)),
                ('op2', models.CharField(max_length=20)),
                ('op3', models.CharField(max_length=20)),
                ('op4', models.CharField(max_length=20)),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quizapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50)),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quizapp.question')),
            ],
        ),
    ]
