# Generated by Django 2.2.6 on 2020-03-24 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20200321_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quizapp.question')),
            ],
        ),
        migrations.RemoveField(
            model_name='options',
            name='question',
        ),
        migrations.DeleteModel(
            name='answer',
        ),
        migrations.DeleteModel(
            name='options',
        ),
    ]
