# Generated by Django 2.2.6 on 2020-03-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20200324_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='result',
        ),
    ]
