# Generated by Django 2.2.6 on 2020-04-25 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200424_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.SmallIntegerField(blank=True, default=0, help_text='In minutes.', validators=[django.core.validators.MaxValueValidator(600)], verbose_name='Time Limit'),
        ),
    ]
